						-- 	CONSULTAS --
-- CONSULTA 1 : SELECCIONA TODOS LOS CLIENTES QUE SE LLAMEN JUAN --
SELECT * FROM clientes WHERE nombresCliente = 'Juan'; -- 1
-- CONSULTA 2 : SELECCIONA TODOS LOS PRODUCTOS CUYO PRECIO DE VENTA ES MAYOR A $10.00 --
SELECT * FROM medicamentos WHERE precioVenta > 10; -- 2
-- ACTUALIZACIÓN 1 : CAMBIA EL NUMERO DE TELEFONO DEL EMPLEADO CON ID=1 --
UPDATE empleados SET telefonoEmpleado = '7807-2350' WHERE idEmpleado = 1; -- 3
-- ACTUALIZACIÓN 2: CAMBIA EL CORREO DEL CLIENTE CON ID 1 --
UPDATE clientes SET correoCliente = 'juanperez5023@example.com' WHERE idCliente = 1; -- 4
-- ELIMINACIÓN: ELIMINAR TODOS LOS REGISTROS EN LA TABLA DETALLE DE VENTA QUE ESTAN RELACIONADOS CON LOS REGISTROS DE VENTAS DEL CLIENTE CON ID=1
DELETE FROM detalleventa WHERE idVenta IN (SELECT idVenta FROM ventas WHERE idCliente = '1');
DELETE FROM ventas WHERE idCliente = '1';
